services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - .:/postgres_docker/semillero/  #directorio local donde se guarda los archivos del contenedor#

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080